name: ssi
description: A tiny implementation of Server Side Includes.
version: 0.1.3  # When changing this, also change lib/version.dart.
repository: https://github.com/filiph/ssi

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  markdown: ^7.3.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  ssi: ssi
